[features]
seeds = false
skip-lint = false
[programs.localnet]
chat_app = "8pW94nJtpxwHmNp1A9hAmTihwQgvGMrp8J5v9ACRsEdC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/gitpod/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
