[features]
seeds = false
skip-lint = false
[programs.localnet]
chat_app = "Fyr6LWcjU2iGGTna5ABWNHeT5ZRqcuFnSE69WXyzAVL1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/gitpod/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
